# Generated by Django 4.2.7 on 2023-11-12 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categories', models.JSONField()),
                ('library', models.JSONField()),
                ('general_description', models.TextField()),
                ('external_link', models.CharField(max_length=355, null=True)),
                ('scales', models.JSONField(null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categories', models.JSONField()),
                ('image', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('optional', models.BooleanField(default=False, null=True)),
                ('type', models.CharField(choices=[('short answer', 'short answer'), ('long answer', 'long answer'), ('scale', 'scale'), ('radio button', 'radio button'), ('checkbox', 'checkbox'), ('drop down', 'drop down'), ('matrix', 'matrix')], max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessment.question')),
                ('columns', models.JSONField()),
                ('matrix_type', models.CharField(max_length=100)),
                ('scores', models.JSONField(null=True)),
                ('options', models.JSONField(null=True)),
            ],
            bases=('assessment.question',),
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessment.question')),
                ('reversed', models.BooleanField(default=False)),
                ('options', models.JSONField()),
            ],
            bases=('assessment.question',),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('guidance', models.TextField(null=True)),
                ('minimum_score', models.IntegerField()),
                ('maximum_score', models.IntegerField()),
                ('key_words', models.JSONField(null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.results')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.results'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assessment.assessment')),
                ('scores', models.ManyToManyField(related_name='scores', to='assessment.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
