# Generated by Django 4.2.7 on 2023-11-12 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=155)),
                ('categories', models.JSONField()),
                ('created_time', models.DateField(auto_now_add=True)),
                ('photo', models.CharField(default='https://firebasestorage.googleapis.com/v0/b/silent-snow-393013.appspot.com/o/groups%2FLogo.png?alt=media&token=db781c28-4187-4e46-937d-f54a40e45f69', max_length=355)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('guideline', models.CharField(max_length=355, null=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], max_length=40)),
                ('forms', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=30)),
                ('reply', models.JSONField(null=True)),
                ('url', models.CharField(max_length=300, null=True)),
                ('size', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mod', 'Mod'), ('member', 'Member')], max_length=30)),
                ('permissions', models.JSONField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportgroups.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=3)),
                ('users', models.JSONField(null=True)),
                ('count', models.IntegerField(default=1)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportgroups.messages')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mod', 'Mod'), ('member', 'Member'), ('pending', 'Pending')], default='member', max_length=30)),
                ('answers', models.JSONField(null=True)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportgroups.groups')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='members', through='supportgroups.GroupsMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='supportgroups.messages'),
        ),
    ]
